import QRCode from'qrcode';import{Resend}from'resend';import{adminClient,response}from'./_shared.mjs';
const arr=v=>Array.isArray(v)?v.filter(Boolean):[];
export async function handler(e){if(e.httpMethod!=='POST')return response(405,{error:'METHOD_NOT_ALLOWED'});let p;try{p=JSON.parse(e.body||'{}')}catch{return response(400,{error:'INVALID_JSON'})}
for(const k of['fullName','companyName','email','phone','industry','language'])if(!String(p[k]||'').trim())return response(400,{error:`${k}_REQUIRED`});
if(!p.privacyConsent)return response(400,{error:'PRIVACY_CONSENT_REQUIRED'});if(!arr(p.plannedVisitDates).length)return response(400,{error:'VISIT_DATE_REQUIRED'});
try{const s=adminClient();const{data,error}=await s.rpc('create_registration_v2',{p_event_code:process.env.EVENT_CODE||'TYF-TYO-AW26',p_full_name:p.fullName,p_roman_name:p.romanName||'',p_company_name:p.companyName,p_company_name_en:p.companyNameEn||'',p_department:p.department||'',p_position_title:p.positionTitle||'',p_email:p.email,p_phone:p.phone,p_country_region:p.countryRegion||'',p_industry:p.industry,p_language:p.language,p_planned_visit_dates:arr(p.plannedVisitDates),p_interest_materials:arr(p.interestMaterials),p_organizer_message:p.organizerMessage||'',p_privacy_consent:!!p.privacyConsent,p_marketing_consent:!!p.marketingConsent,p_policy_version:'2026-07-26'});
if(error){if(String(error.message).includes('ALREADY_REGISTERED'))return response(409,{error:'ALREADY_REGISTERED',message:p.language==='en'?'This email is already registered.':'このメールアドレスは既に登録されています。'});throw error}
const x=Array.isArray(data)?data[0]:data,site=(process.env.PUBLIC_SITE_URL||'').replace(/\/$/,'');const qrUrl=`${site}/checkin.html?token=${x.qrToken}`;
const buf=await QRCode.toBuffer(qrUrl,{width:420,margin:2,errorCorrectionLevel:'M',color:{dark:'#4B1E3F',light:'#FFFFFF'}});let emailSent=false;
if(process.env.RESEND_API_KEY&&process.env.FROM_EMAIL){const r=new Resend(process.env.RESEND_API_KEY);const ja=p.language==='ja';const{error:me}=await r.emails.send({from:process.env.FROM_EMAIL,to:[p.email],subject:ja?'【THE YARN FAIR IN TOKYO™】来場登録完了':'Visitor registration complete | THE YARN FAIR IN TOKYO™',html:`<div style="font-family:Arial;line-height:1.7;color:#4B1E3F"><h2>THE YARN FAIR IN TOKYO™</h2><p>${ja?p.fullName+' 様':'Dear '+p.fullName+','}</p><p>${ja?'来場登録が完了しました。':'Your registration is complete.'}</p><p><strong>${ja?'受付番号':'Registration No.'}:</strong> ${x.registrationNumber}</p><p><img src="cid:visitor-qr" width="260"></p></div>`,attachments:[{content:buf.toString('base64'),filename:'visitor-qr.png',contentId:'visitor-qr'}]});emailSent=!me}
return response(201,{registrationNumber:x.registrationNumber,qrToken:x.qrToken,qrDataUrl:`data:image/png;base64,${buf.toString('base64')}`,emailSent})}catch(err){console.error(err);return response(500,{error:'REGISTRATION_FAILED',message:'Registration could not be completed.'})}}
